# Generated by Django 6.0.4 on 2026-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
        ('orders', '0003_alter_order_status'),
        ('products', '0002_rename_quantity_product_quantitys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_itmems',
            new_name='OrderItem',
        ),
    ]
